# Generated by Django 4.1.5 on 2023-02-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_logged_in', models.BooleanField(default=False)),
                ('logged_in_at', models.DateTimeField(auto_now=True)),
                ('logged_in_ip', models.GenericIPAddressField()),
                ('has_email_verified', models.BooleanField(default=False)),
                ('has_phone_verified', models.BooleanField(default=False)),
                ('has_KYC_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mysite.userinfo')),
                ('balance', models.IntegerField(default=0)),
                ('num_coins', models.IntegerField(default=0)),
                ('num_diamonds', models.IntegerField(default=0)),
                ('num_tickets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mysite.userinfo')),
                ('level', models.IntegerField(default=0)),
                ('level_progress', models.IntegerField(default=0)),
                ('num_friends_invited', models.IntegerField(default=0)),
                ('num_friends_joined', models.IntegerField(default=0)),
                ('num_videos_watched', models.IntegerField(default=0)),
                ('dig_speed', models.IntegerField(default=0.5)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('friends_list', models.ManyToManyField(blank=True, to='mysite.userlevel')),
            ],
        ),
    ]
